// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/mapper.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/mapper.go -destination=internal/infra/read/redis/gig_event_mapper_mock_test.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	domain "gig-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGigEventMapper is a mock of GigEventMapper interface.
type MockGigEventMapper struct {
	ctrl     *gomock.Controller
	recorder *MockGigEventMapperMockRecorder
	isgomock struct{}
}

// MockGigEventMapperMockRecorder is the mock recorder for MockGigEventMapper.
type MockGigEventMapperMockRecorder struct {
	mock *MockGigEventMapper
}

// NewMockGigEventMapper creates a new mock instance.
func NewMockGigEventMapper(ctrl *gomock.Controller) *MockGigEventMapper {
	mock := &MockGigEventMapper{ctrl: ctrl}
	mock.recorder = &MockGigEventMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigEventMapper) EXPECT() *MockGigEventMapperMockRecorder {
	return m.recorder
}

// FromPublishedPayload mocks base method.
func (m *MockGigEventMapper) FromPublishedPayload(payload []byte) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromPublishedPayload", payload)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromPublishedPayload indicates an expected call of FromPublishedPayload.
func (mr *MockGigEventMapperMockRecorder) FromPublishedPayload(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromPublishedPayload", reflect.TypeOf((*MockGigEventMapper)(nil).FromPublishedPayload), payload)
}

// ToPublishedPayload mocks base method.
func (m *MockGigEventMapper) ToPublishedPayload(gig *domain.Gig) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToPublishedPayload", gig)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToPublishedPayload indicates an expected call of ToPublishedPayload.
func (mr *MockGigEventMapperMockRecorder) ToPublishedPayload(gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToPublishedPayload", reflect.TypeOf((*MockGigEventMapper)(nil).ToPublishedPayload), gig)
}

// FromReadModelPayload mocks base method.
func (m *MockGigEventMapper) FromReadModelPayload(payload []byte) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromReadModelPayload", payload)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromReadModelPayload indicates an expected call of FromReadModelPayload.
func (mr *MockGigEventMapperMockRecorder) FromReadModelPayload(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromReadModelPayload", reflect.TypeOf((*MockGigEventMapper)(nil).FromReadModelPayload), payload)
}

// ToReadModelPayload mocks base method.
func (m *MockGigEventMapper) ToReadModelPayload(gig *domain.Gig) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToReadModelPayload", gig)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToReadModelPayload indicates an expected call of ToReadModelPayload.
func (mr *MockGigEventMapperMockRecorder) ToReadModelPayload(gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToReadModelPayload", reflect.TypeOf((*MockGigEventMapper)(nil).ToReadModelPayload), gig)
}
