// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gig.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gig.go -destination=internal/application/gig_repository_mock_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	domain "gig-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGigRepository is a mock of GigRepository interface.
type MockGigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGigRepositoryMockRecorder
	isgomock struct{}
}

// MockGigRepositoryMockRecorder is the mock recorder for MockGigRepository.
type MockGigRepositoryMockRecorder struct {
	mock *MockGigRepository
}

// NewMockGigRepository creates a new mock instance.
func NewMockGigRepository(ctrl *gomock.Controller) *MockGigRepository {
	mock := &MockGigRepository{ctrl: ctrl}
	mock.recorder = &MockGigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigRepository) EXPECT() *MockGigRepositoryMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockGigRepository) CreateDraft(ctx context.Context, params domain.CreateDraftParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockGigRepositoryMockRecorder) CreateDraft(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockGigRepository)(nil).CreateDraft), ctx, params)
}

// GetByID mocks base method.
func (m *MockGigRepository) GetByID(ctx context.Context, gigID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigRepositoryMockRecorder) GetByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigRepository)(nil).GetByID), ctx, gigID)
}

// Publish mocks base method.
func (m *MockGigRepository) Publish(ctx context.Context, gigID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, gigID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockGigRepositoryMockRecorder) Publish(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGigRepository)(nil).Publish), ctx, gigID)
}

// ReplaceMedia mocks base method.
func (m *MockGigRepository) ReplaceMedia(ctx context.Context, gigID string, params domain.ReplaceMediaParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMedia", ctx, gigID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceMedia indicates an expected call of ReplaceMedia.
func (mr *MockGigRepositoryMockRecorder) ReplaceMedia(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMedia", reflect.TypeOf((*MockGigRepository)(nil).ReplaceMedia), ctx, gigID, params)
}

// ReplacePackages mocks base method.
func (m *MockGigRepository) ReplacePackages(ctx context.Context, gigID string, params domain.ReplacePackagesParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePackages", ctx, gigID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePackages indicates an expected call of ReplacePackages.
func (mr *MockGigRepositoryMockRecorder) ReplacePackages(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePackages", reflect.TypeOf((*MockGigRepository)(nil).ReplacePackages), ctx, gigID, params)
}

// ReplaceQuestions mocks base method.
func (m *MockGigRepository) ReplaceQuestions(ctx context.Context, gigID string, params domain.ReplaceQuestionsParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceQuestions", ctx, gigID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceQuestions indicates an expected call of ReplaceQuestions.
func (mr *MockGigRepositoryMockRecorder) ReplaceQuestions(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceQuestions", reflect.TypeOf((*MockGigRepository)(nil).ReplaceQuestions), ctx, gigID, params)
}

// UpdateBasicInfo mocks base method.
func (m *MockGigRepository) UpdateBasicInfo(ctx context.Context, gigID string, params domain.UpdateBasicInfoParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicInfo", ctx, gigID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicInfo indicates an expected call of UpdateBasicInfo.
func (mr *MockGigRepositoryMockRecorder) UpdateBasicInfo(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicInfo", reflect.TypeOf((*MockGigRepository)(nil).UpdateBasicInfo), ctx, gigID, params)
}

// MockGigReadRepository is a mock of GigReadRepository interface.
type MockGigReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGigReadRepositoryMockRecorder
	isgomock struct{}
}

// MockGigReadRepositoryMockRecorder is the mock recorder for MockGigReadRepository.
type MockGigReadRepositoryMockRecorder struct {
	mock *MockGigReadRepository
}

// NewMockGigReadRepository creates a new mock instance.
func NewMockGigReadRepository(ctrl *gomock.Controller) *MockGigReadRepository {
	mock := &MockGigReadRepository{ctrl: ctrl}
	mock.recorder = &MockGigReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigReadRepository) EXPECT() *MockGigReadRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockGigReadRepository) DeleteByID(ctx context.Context, gigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, gigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockGigReadRepositoryMockRecorder) DeleteByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockGigReadRepository)(nil).DeleteByID), ctx, gigID)
}

// GetByID mocks base method.
func (m *MockGigReadRepository) GetByID(ctx context.Context, gigID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigReadRepositoryMockRecorder) GetByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigReadRepository)(nil).GetByID), ctx, gigID)
}

// Upsert mocks base method.
func (m *MockGigReadRepository) Upsert(ctx context.Context, gig *domain.Gig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, gig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockGigReadRepositoryMockRecorder) Upsert(ctx, gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockGigReadRepository)(nil).Upsert), ctx, gig)
}
