// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/type.go -destination=internal/application/mock_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	domain "gig-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventBroker is a mock of EventBroker interface.
type MockEventBroker struct {
	ctrl     *gomock.Controller
	recorder *MockEventBrokerMockRecorder
	isgomock struct{}
}

// MockEventBrokerMockRecorder is the mock recorder for MockEventBroker.
type MockEventBrokerMockRecorder struct {
	mock *MockEventBroker
}

// NewMockEventBroker creates a new mock instance.
func NewMockEventBroker(ctrl *gomock.Controller) *MockEventBroker {
	mock := &MockEventBroker{ctrl: ctrl}
	mock.recorder = &MockEventBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBroker) EXPECT() *MockEventBrokerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventBroker) Publish(ctx context.Context, subject string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventBrokerMockRecorder) Publish(ctx, subject, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventBroker)(nil).Publish), ctx, subject, payload)
}

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
	isgomock struct{}
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(ctx context.Context, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), ctx, fileID)
}

// UploadFiles mocks base method.
func (m *MockFileService) UploadFiles(ctx context.Context, ownerID, prefix string, files []domain.MediaUpload) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFiles", ctx, ownerID, prefix, files)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockFileServiceMockRecorder) UploadFiles(ctx, ownerID, prefix, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockFileService)(nil).UploadFiles), ctx, ownerID, prefix, files)
}

// MockConnectStatusChecker is a mock of ConnectStatusChecker interface.
type MockConnectStatusChecker struct {
	ctrl     *gomock.Controller
	recorder *MockConnectStatusCheckerMockRecorder
	isgomock struct{}
}

// MockConnectStatusCheckerMockRecorder is the mock recorder for MockConnectStatusChecker.
type MockConnectStatusCheckerMockRecorder struct {
	mock *MockConnectStatusChecker
}

// NewMockConnectStatusChecker creates a new mock instance.
func NewMockConnectStatusChecker(ctrl *gomock.Controller) *MockConnectStatusChecker {
	mock := &MockConnectStatusChecker{ctrl: ctrl}
	mock.recorder = &MockConnectStatusCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectStatusChecker) EXPECT() *MockConnectStatusCheckerMockRecorder {
	return m.recorder
}

// GetConnectStatus mocks base method.
func (m *MockConnectStatusChecker) GetConnectStatus(ctx context.Context, userID string) (*ConnectStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectStatus", ctx, userID)
	ret0, _ := ret[0].(*ConnectStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectStatus indicates an expected call of GetConnectStatus.
func (mr *MockConnectStatusCheckerMockRecorder) GetConnectStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectStatus", reflect.TypeOf((*MockConnectStatusChecker)(nil).GetConnectStatus), ctx, userID)
}

// MockSlugger is a mock of Slugger interface.
type MockSlugger struct {
	ctrl     *gomock.Controller
	recorder *MockSluggerMockRecorder
	isgomock struct{}
}

// MockSluggerMockRecorder is the mock recorder for MockSlugger.
type MockSluggerMockRecorder struct {
	mock *MockSlugger
}

// NewMockSlugger creates a new mock instance.
func NewMockSlugger(ctrl *gomock.Controller) *MockSlugger {
	mock := &MockSlugger{ctrl: ctrl}
	mock.recorder = &MockSluggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugger) EXPECT() *MockSluggerMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSlugger) Generate(title string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", title)
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockSluggerMockRecorder) Generate(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSlugger)(nil).Generate), title)
}

// MockGigService is a mock of GigService interface.
type MockGigService struct {
	ctrl     *gomock.Controller
	recorder *MockGigServiceMockRecorder
	isgomock struct{}
}

// MockGigServiceMockRecorder is the mock recorder for MockGigService.
type MockGigServiceMockRecorder struct {
	mock *MockGigService
}

// NewMockGigService creates a new mock instance.
func NewMockGigService(ctrl *gomock.Controller) *MockGigService {
	mock := &MockGigService{ctrl: ctrl}
	mock.recorder = &MockGigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigService) EXPECT() *MockGigServiceMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockGigService) CreateDraft(ctx context.Context, freelancerID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, freelancerID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockGigServiceMockRecorder) CreateDraft(ctx, freelancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockGigService)(nil).CreateDraft), ctx, freelancerID)
}

// GetByID mocks base method.
func (m *MockGigService) GetByID(ctx context.Context, gigID, freelancerID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID, freelancerID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigServiceMockRecorder) GetByID(ctx, gigID, freelancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigService)(nil).GetByID), ctx, gigID, freelancerID)
}

// GetOrderStartSnapshot mocks base method.
func (m *MockGigService) GetOrderStartSnapshot(ctx context.Context, gigID, packageID string) (*OrderStartSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStartSnapshot", ctx, gigID, packageID)
	ret0, _ := ret[0].(*OrderStartSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStartSnapshot indicates an expected call of GetOrderStartSnapshot.
func (mr *MockGigServiceMockRecorder) GetOrderStartSnapshot(ctx, gigID, packageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStartSnapshot", reflect.TypeOf((*MockGigService)(nil).GetOrderStartSnapshot), ctx, gigID, packageID)
}

// Publish mocks base method.
func (m *MockGigService) Publish(ctx context.Context, gigID, freelancerID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, gigID, freelancerID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockGigServiceMockRecorder) Publish(ctx, gigID, freelancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGigService)(nil).Publish), ctx, gigID, freelancerID)
}

// ReplaceMedia mocks base method.
func (m *MockGigService) ReplaceMedia(ctx context.Context, gigID, freelancerID string, params domain.ReplaceMediaUploadParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMedia", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceMedia indicates an expected call of ReplaceMedia.
func (mr *MockGigServiceMockRecorder) ReplaceMedia(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMedia", reflect.TypeOf((*MockGigService)(nil).ReplaceMedia), ctx, gigID, freelancerID, params)
}

// ReplacePackages mocks base method.
func (m *MockGigService) ReplacePackages(ctx context.Context, gigID, freelancerID string, params domain.ReplacePackagesParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePackages", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePackages indicates an expected call of ReplacePackages.
func (mr *MockGigServiceMockRecorder) ReplacePackages(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePackages", reflect.TypeOf((*MockGigService)(nil).ReplacePackages), ctx, gigID, freelancerID, params)
}

// ReplaceQuestions mocks base method.
func (m *MockGigService) ReplaceQuestions(ctx context.Context, gigID, freelancerID string, params domain.ReplaceQuestionsParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceQuestions", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceQuestions indicates an expected call of ReplaceQuestions.
func (mr *MockGigServiceMockRecorder) ReplaceQuestions(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceQuestions", reflect.TypeOf((*MockGigService)(nil).ReplaceQuestions), ctx, gigID, freelancerID, params)
}

// UpdateBasicInfo mocks base method.
func (m *MockGigService) UpdateBasicInfo(ctx context.Context, gigID, freelancerID string, params domain.UpdateBasicInfoParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicInfo", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicInfo indicates an expected call of UpdateBasicInfo.
func (mr *MockGigServiceMockRecorder) UpdateBasicInfo(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicInfo", reflect.TypeOf((*MockGigService)(nil).UpdateBasicInfo), ctx, gigID, freelancerID, params)
}
