// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/type.go -destination=internal/presentation/grpc/gig_service_mock_test.go -package=grpc
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	service "gig-service/internal/application"
	domain "gig-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventBroker is a mock of EventBroker interface.
type MockEventBroker struct {
	ctrl     *gomock.Controller
	recorder *MockEventBrokerMockRecorder
	isgomock struct{}
}

// MockEventBrokerMockRecorder is the mock recorder for MockEventBroker.
type MockEventBrokerMockRecorder struct {
	mock *MockEventBroker
}

// NewMockEventBroker creates a new mock instance.
func NewMockEventBroker(ctrl *gomock.Controller) *MockEventBroker {
	mock := &MockEventBroker{ctrl: ctrl}
	mock.recorder = &MockEventBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBroker) EXPECT() *MockEventBrokerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventBroker) Publish(ctx context.Context, subject string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventBrokerMockRecorder) Publish(ctx, subject, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventBroker)(nil).Publish), ctx, subject, payload)
}

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
	isgomock struct{}
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(ctx context.Context, fileID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), ctx, fileID)
}

// GetFileURL mocks base method.
func (m *MockFileService) GetFileURL(ctx context.Context, fileID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileURL", ctx, fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileURL indicates an expected call of GetFileURL.
func (mr *MockFileServiceMockRecorder) GetFileURL(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileURL", reflect.TypeOf((*MockFileService)(nil).GetFileURL), ctx, fileID)
}

// GetFileURLs mocks base method.
func (m *MockFileService) GetFileURLs(ctx context.Context, fileIDs []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileURLs", ctx, fileIDs)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileURLs indicates an expected call of GetFileURLs.
func (mr *MockFileServiceMockRecorder) GetFileURLs(ctx, fileIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileURLs", reflect.TypeOf((*MockFileService)(nil).GetFileURLs), ctx, fileIDs)
}

// UploadFiles mocks base method.
func (m *MockFileService) UploadFiles(ctx context.Context, ownerID, prefix string, files []domain.MediaUpload) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFiles", ctx, ownerID, prefix, files)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFiles indicates an expected call of UploadFiles.
func (mr *MockFileServiceMockRecorder) UploadFiles(ctx, ownerID, prefix, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFiles", reflect.TypeOf((*MockFileService)(nil).UploadFiles), ctx, ownerID, prefix, files)
}

// MockConnectStatusChecker is a mock of ConnectStatusChecker interface.
type MockConnectStatusChecker struct {
	ctrl     *gomock.Controller
	recorder *MockConnectStatusCheckerMockRecorder
	isgomock struct{}
}

// MockConnectStatusCheckerMockRecorder is the mock recorder for MockConnectStatusChecker.
type MockConnectStatusCheckerMockRecorder struct {
	mock *MockConnectStatusChecker
}

// NewMockConnectStatusChecker creates a new mock instance.
func NewMockConnectStatusChecker(ctrl *gomock.Controller) *MockConnectStatusChecker {
	mock := &MockConnectStatusChecker{ctrl: ctrl}
	mock.recorder = &MockConnectStatusCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectStatusChecker) EXPECT() *MockConnectStatusCheckerMockRecorder {
	return m.recorder
}

// GetConnectStatus mocks base method.
func (m *MockConnectStatusChecker) GetConnectStatus(ctx context.Context, userID string) (*service.ConnectStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectStatus", ctx, userID)
	ret0, _ := ret[0].(*service.ConnectStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectStatus indicates an expected call of GetConnectStatus.
func (mr *MockConnectStatusCheckerMockRecorder) GetConnectStatus(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectStatus", reflect.TypeOf((*MockConnectStatusChecker)(nil).GetConnectStatus), ctx, userID)
}

// MockSlugger is a mock of Slugger interface.
type MockSlugger struct {
	ctrl     *gomock.Controller
	recorder *MockSluggerMockRecorder
	isgomock struct{}
}

// MockSluggerMockRecorder is the mock recorder for MockSlugger.
type MockSluggerMockRecorder struct {
	mock *MockSlugger
}

// NewMockSlugger creates a new mock instance.
func NewMockSlugger(ctrl *gomock.Controller) *MockSlugger {
	mock := &MockSlugger{ctrl: ctrl}
	mock.recorder = &MockSluggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugger) EXPECT() *MockSluggerMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSlugger) Generate(title, gigID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", title, gigID)
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockSluggerMockRecorder) Generate(title, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSlugger)(nil).Generate), title, gigID)
}

// MockGigService is a mock of GigService interface.
type MockGigService struct {
	ctrl     *gomock.Controller
	recorder *MockGigServiceMockRecorder
	isgomock struct{}
}

// MockGigServiceMockRecorder is the mock recorder for MockGigService.
type MockGigServiceMockRecorder struct {
	mock *MockGigService
}

// NewMockGigService creates a new mock instance.
func NewMockGigService(ctrl *gomock.Controller) *MockGigService {
	mock := &MockGigService{ctrl: ctrl}
	mock.recorder = &MockGigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigService) EXPECT() *MockGigServiceMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockGigService) CreateDraft(ctx context.Context, freelancerID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, freelancerID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockGigServiceMockRecorder) CreateDraft(ctx, freelancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockGigService)(nil).CreateDraft), ctx, freelancerID)
}

// GetByID mocks base method.
func (m *MockGigService) GetByID(ctx context.Context, gigID, freelancerID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID, freelancerID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigServiceMockRecorder) GetByID(ctx, gigID, freelancerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigService)(nil).GetByID), ctx, gigID, freelancerID)
}

// GetOrderStartSnapshot mocks base method.
func (m *MockGigService) GetOrderStartSnapshot(ctx context.Context, gigID, packageID string) (*service.OrderStartSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStartSnapshot", ctx, gigID, packageID)
	ret0, _ := ret[0].(*service.OrderStartSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStartSnapshot indicates an expected call of GetOrderStartSnapshot.
func (mr *MockGigServiceMockRecorder) GetOrderStartSnapshot(ctx, gigID, packageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStartSnapshot", reflect.TypeOf((*MockGigService)(nil).GetOrderStartSnapshot), ctx, gigID, packageID)
}

// GetPreviewGigsByFreelancerUsername mocks base method.
func (m *MockGigService) GetPreviewGigsByFreelancerUsername(ctx context.Context, query domain.ListPreviewGigsQuery) (*domain.ListPreviewGigsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviewGigsByFreelancerUsername", ctx, query)
	ret0, _ := ret[0].(*domain.ListPreviewGigsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviewGigsByFreelancerUsername indicates an expected call of GetPreviewGigsByFreelancerUsername.
func (mr *MockGigServiceMockRecorder) GetPreviewGigsByFreelancerUsername(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviewGigsByFreelancerUsername", reflect.TypeOf((*MockGigService)(nil).GetPreviewGigsByFreelancerUsername), ctx, query)
}

// AppendPreviewGig mocks base method.
func (m *MockGigService) AppendPreviewGig(ctx context.Context, gig *domain.Gig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendPreviewGig", ctx, gig)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendPreviewGig indicates an expected call of AppendPreviewGig.
func (mr *MockGigServiceMockRecorder) AppendPreviewGig(ctx, gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendPreviewGig", reflect.TypeOf((*MockGigService)(nil).AppendPreviewGig), ctx, gig)
}

// RebuildPopularitySnapshots mocks base method.
func (m *MockGigService) RebuildPopularitySnapshots(ctx context.Context, gigs []*domain.Gig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebuildPopularitySnapshots", ctx, gigs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebuildPopularitySnapshots indicates an expected call of RebuildPopularitySnapshots.
func (mr *MockGigServiceMockRecorder) RebuildPopularitySnapshots(ctx, gigs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebuildPopularitySnapshots", reflect.TypeOf((*MockGigService)(nil).RebuildPopularitySnapshots), ctx, gigs)
}

// GetPublicByID mocks base method.
func (m *MockGigService) GetPublicByID(ctx context.Context, gigID string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicByID", ctx, gigID)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicByID indicates an expected call of GetPublicByID.
func (mr *MockGigServiceMockRecorder) GetPublicByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicByID", reflect.TypeOf((*MockGigService)(nil).GetPublicByID), ctx, gigID)
}

// Project mocks base method.
func (m *MockGigService) Project(ctx context.Context, gig *domain.Gig) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Project", ctx, gig)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Project indicates an expected call of Project.
func (mr *MockGigServiceMockRecorder) Project(ctx, gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Project", reflect.TypeOf((*MockGigService)(nil).Project), ctx, gig)
}

// Publish mocks base method.
func (m *MockGigService) Publish(ctx context.Context, gigID, freelancerID, username string) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, gigID, freelancerID, username)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockGigServiceMockRecorder) Publish(ctx, gigID, freelancerID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGigService)(nil).Publish), ctx, gigID, freelancerID, username)
}

// ReplaceMedia mocks base method.
func (m *MockGigService) ReplaceMedia(ctx context.Context, gigID, freelancerID string, params domain.ReplaceMediaUploadParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMedia", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceMedia indicates an expected call of ReplaceMedia.
func (mr *MockGigServiceMockRecorder) ReplaceMedia(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMedia", reflect.TypeOf((*MockGigService)(nil).ReplaceMedia), ctx, gigID, freelancerID, params)
}

// ReplacePackages mocks base method.
func (m *MockGigService) ReplacePackages(ctx context.Context, gigID, freelancerID string, params domain.ReplacePackagesParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePackages", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePackages indicates an expected call of ReplacePackages.
func (mr *MockGigServiceMockRecorder) ReplacePackages(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePackages", reflect.TypeOf((*MockGigService)(nil).ReplacePackages), ctx, gigID, freelancerID, params)
}

// ReplaceQuestions mocks base method.
func (m *MockGigService) ReplaceQuestions(ctx context.Context, gigID, freelancerID string, params domain.ReplaceQuestionsParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceQuestions", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceQuestions indicates an expected call of ReplaceQuestions.
func (mr *MockGigServiceMockRecorder) ReplaceQuestions(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceQuestions", reflect.TypeOf((*MockGigService)(nil).ReplaceQuestions), ctx, gigID, freelancerID, params)
}

// UpdateBasicInfo mocks base method.
func (m *MockGigService) UpdateBasicInfo(ctx context.Context, gigID, freelancerID string, params domain.UpdateBasicInfoParams) (*domain.Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicInfo", ctx, gigID, freelancerID, params)
	ret0, _ := ret[0].(*domain.Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicInfo indicates an expected call of UpdateBasicInfo.
func (mr *MockGigServiceMockRecorder) UpdateBasicInfo(ctx, gigID, freelancerID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicInfo", reflect.TypeOf((*MockGigService)(nil).UpdateBasicInfo), ctx, gigID, freelancerID, params)
}
