// Code generated by MockGen. DO NOT EDIT.
// Source: internal/presentation/event_broker/nats/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/presentation/event_broker/nats/type.go -destination=internal/presentation/event_broker/nats/mock_test.go -package=nats
//

// Package nats is a generated GoMock package.
package nats

import (
	context "context"
	config "gig-service/config"
	domain "gig-service/internal/domain"
	event_broker "gig-service/internal/presentation/event_broker"
	reflect "reflect"

	nats_go "github.com/nats-io/nats.go"
	logging "github.com/ofm-microseervices/ofm-common/pkg/logging"
	gomock "go.uber.org/mock/gomock"
)

// MockGigProjectionSubscriber is a mock of GigProjectionSubscriber interface.
type MockGigProjectionSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockGigProjectionSubscriberMockRecorder
	isgomock struct{}
}

// MockGigProjectionSubscriberMockRecorder is the mock recorder for MockGigProjectionSubscriber.
type MockGigProjectionSubscriberMockRecorder struct {
	mock *MockGigProjectionSubscriber
}

// NewMockGigProjectionSubscriber creates a new mock instance.
func NewMockGigProjectionSubscriber(ctrl *gomock.Controller) *MockGigProjectionSubscriber {
	mock := &MockGigProjectionSubscriber{ctrl: ctrl}
	mock.recorder = &MockGigProjectionSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigProjectionSubscriber) EXPECT() *MockGigProjectionSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockGigProjectionSubscriber) Subscribe(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockGigProjectionSubscriberMockRecorder) Subscribe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockGigProjectionSubscriber)(nil).Subscribe), ctx)
}

// MockProjectionWriter is a mock of ProjectionWriter interface.
type MockProjectionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProjectionWriterMockRecorder
	isgomock struct{}
}

// MockProjectionWriterMockRecorder is the mock recorder for MockProjectionWriter.
type MockProjectionWriterMockRecorder struct {
	mock *MockProjectionWriter
}

// NewMockProjectionWriter creates a new mock instance.
func NewMockProjectionWriter(ctrl *gomock.Controller) *MockProjectionWriter {
	mock := &MockProjectionWriter{ctrl: ctrl}
	mock.recorder = &MockProjectionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectionWriter) EXPECT() *MockProjectionWriterMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockProjectionWriter) DeleteByID(ctx context.Context, gigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, gigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockProjectionWriterMockRecorder) DeleteByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockProjectionWriter)(nil).DeleteByID), ctx, gigID)
}

// Upsert mocks base method.
func (m *MockProjectionWriter) Upsert(ctx context.Context, gig *domain.Gig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, gig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProjectionWriterMockRecorder) Upsert(ctx, gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProjectionWriter)(nil).Upsert), ctx, gig)
}

// MockPullConsumerConfigValidator is a mock of PullConsumerConfigValidator interface.
type MockPullConsumerConfigValidator struct {
	ctrl     *gomock.Controller
	recorder *MockPullConsumerConfigValidatorMockRecorder
	isgomock struct{}
}

// MockPullConsumerConfigValidatorMockRecorder is the mock recorder for MockPullConsumerConfigValidator.
type MockPullConsumerConfigValidatorMockRecorder struct {
	mock *MockPullConsumerConfigValidator
}

// NewMockPullConsumerConfigValidator creates a new mock instance.
func NewMockPullConsumerConfigValidator(ctrl *gomock.Controller) *MockPullConsumerConfigValidator {
	mock := &MockPullConsumerConfigValidator{ctrl: ctrl}
	mock.recorder = &MockPullConsumerConfigValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullConsumerConfigValidator) EXPECT() *MockPullConsumerConfigValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockPullConsumerConfigValidator) Validate(cfg config.PullConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockPullConsumerConfigValidatorMockRecorder) Validate(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockPullConsumerConfigValidator)(nil).Validate), cfg)
}

// MockPullConsumerRuntime is a mock of PullConsumerRuntime interface.
type MockPullConsumerRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockPullConsumerRuntimeMockRecorder
	isgomock struct{}
}

// MockPullConsumerRuntimeMockRecorder is the mock recorder for MockPullConsumerRuntime.
type MockPullConsumerRuntimeMockRecorder struct {
	mock *MockPullConsumerRuntime
}

// NewMockPullConsumerRuntime creates a new mock instance.
func NewMockPullConsumerRuntime(ctrl *gomock.Controller) *MockPullConsumerRuntime {
	mock := &MockPullConsumerRuntime{ctrl: ctrl}
	mock.recorder = &MockPullConsumerRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullConsumerRuntime) EXPECT() *MockPullConsumerRuntimeMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockPullConsumerRuntime) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockPullConsumerRuntimeMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPullConsumerRuntime)(nil).Start), ctx)
}

// MockPullConsumerRuntimeFactory is a mock of PullConsumerRuntimeFactory interface.
type MockPullConsumerRuntimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockPullConsumerRuntimeFactoryMockRecorder
	isgomock struct{}
}

// MockPullConsumerRuntimeFactoryMockRecorder is the mock recorder for MockPullConsumerRuntimeFactory.
type MockPullConsumerRuntimeFactoryMockRecorder struct {
	mock *MockPullConsumerRuntimeFactory
}

// NewMockPullConsumerRuntimeFactory creates a new mock instance.
func NewMockPullConsumerRuntimeFactory(ctrl *gomock.Controller) *MockPullConsumerRuntimeFactory {
	mock := &MockPullConsumerRuntimeFactory{ctrl: ctrl}
	mock.recorder = &MockPullConsumerRuntimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullConsumerRuntimeFactory) EXPECT() *MockPullConsumerRuntimeFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullConsumerRuntimeFactory) Create(nc *nats_go.Conn, log logging.Logger, cfg config.PullConsumerConfig, handler event_broker.MessageHandler) (PullConsumerRuntime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", nc, log, cfg, handler)
	ret0, _ := ret[0].(PullConsumerRuntime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullConsumerRuntimeFactoryMockRecorder) Create(nc, log, cfg, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullConsumerRuntimeFactory)(nil).Create), nc, log, cfg, handler)
}
