package domain

import "errors"

var (
	ErrInvalidGigID                = errors.New("invalid gig id")
	ErrInvalidGigSlug              = errors.New("invalid gig slug")
	ErrInvalidFreelancerID         = errors.New("invalid freelancer id")
	ErrInvalidUsername             = errors.New("invalid username")
	ErrInvalidTitle                = errors.New("invalid title")
	ErrInvalidShortInfo            = errors.New("invalid short info")
	ErrInvalidDescription          = errors.New("invalid description")
	ErrInvalidCategoryID           = errors.New("invalid category id")
	ErrInvalidCurrency             = errors.New("invalid currency")
	ErrInvalidPackageTier          = errors.New("invalid package tier")
	ErrInvalidPackageDescription   = errors.New("invalid package description")
	ErrInvalidPackageDeliveryDays  = errors.New("invalid package delivery days")
	ErrInvalidPackagePriceCents    = errors.New("invalid package price cents")
	ErrInvalidQuestionContent      = errors.New("invalid question content")
	ErrInvalidMediaUpload          = errors.New("invalid media upload")
	ErrInvalidFileID               = errors.New("invalid file id")
	ErrInvalidMediaRef             = ErrInvalidFileID
	ErrInvalidGigListStatus        = errors.New("invalid gig list status")
	ErrInvalidGigListSort          = errors.New("invalid gig list sort")
	ErrInvalidGigListOrder         = errors.New("invalid gig list order")
	ErrInvalidGigListPage          = errors.New("invalid gig list page")
	ErrInvalidGigListLimit         = errors.New("invalid gig list limit")
	ErrInvalidPackageCount         = errors.New("invalid package count")
	ErrInvalidGigState             = errors.New("invalid gig state")
	ErrConnectOnboardingIncomplete = errors.New("connect onboarding incomplete")
	ErrGigNotFound                 = errors.New("gig not found")
	ErrGigAlreadyExists            = errors.New("gig already exists")
	ErrGigDraftIncomplete          = errors.New("gig draft is incomplete")
	ErrGigAlreadyPublished         = errors.New("gig already published")
	ErrFailedToCreateGig           = errors.New("failed to create gig")
	ErrFailedToUpdateGig           = errors.New("failed to update gig")
	ErrFailedToPublishGig          = errors.New("failed to publish gig")
	ErrFailedToFindGig             = errors.New("failed to find gig")
	ErrFailedToReplaceGigPackages  = errors.New("failed to replace gig packages")
	ErrFailedToReplaceGigQuestions = errors.New("failed to replace gig questions")
	ErrFailedToReplaceGigMedia     = errors.New("failed to replace gig media")
)
