// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gig.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gig.go -destination=internal/domain/mock_test.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockGigRepository is a mock of GigRepository interface.
type MockGigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGigRepositoryMockRecorder
	isgomock struct{}
}

// MockGigRepositoryMockRecorder is the mock recorder for MockGigRepository.
type MockGigRepositoryMockRecorder struct {
	mock *MockGigRepository
}

// NewMockGigRepository creates a new mock instance.
func NewMockGigRepository(ctrl *gomock.Controller) *MockGigRepository {
	mock := &MockGigRepository{ctrl: ctrl}
	mock.recorder = &MockGigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigRepository) EXPECT() *MockGigRepositoryMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockGigRepository) CreateDraft(ctx context.Context, params CreateDraftParams) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, params)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockGigRepositoryMockRecorder) CreateDraft(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockGigRepository)(nil).CreateDraft), ctx, params)
}

// GetByID mocks base method.
func (m *MockGigRepository) GetByID(ctx context.Context, gigID string) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigRepositoryMockRecorder) GetByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigRepository)(nil).GetByID), ctx, gigID)
}

// ListAll mocks base method.
func (m *MockGigRepository) ListAll(ctx context.Context) ([]*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGigRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGigRepository)(nil).ListAll), ctx)
}

// ListPublishedBySellerUsername mocks base method.
func (m *MockGigRepository) ListPublishedBySellerUsername(ctx context.Context, query ListPreviewGigsQuery) ([]*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedBySellerUsername", ctx, query)
	ret0, _ := ret[0].([]*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedBySellerUsername indicates an expected call of ListPublishedBySellerUsername.
func (mr *MockGigRepositoryMockRecorder) ListPublishedBySellerUsername(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedBySellerUsername", reflect.TypeOf((*MockGigRepository)(nil).ListPublishedBySellerUsername), ctx, query)
}

// Publish mocks base method.
func (m *MockGigRepository) Publish(ctx context.Context, gigID string) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, gigID)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockGigRepositoryMockRecorder) Publish(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGigRepository)(nil).Publish), ctx, gigID)
}

// ReplaceMedia mocks base method.
func (m *MockGigRepository) ReplaceMedia(ctx context.Context, gigID string, params ReplaceMediaParams) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMedia", ctx, gigID, params)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceMedia indicates an expected call of ReplaceMedia.
func (mr *MockGigRepositoryMockRecorder) ReplaceMedia(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMedia", reflect.TypeOf((*MockGigRepository)(nil).ReplaceMedia), ctx, gigID, params)
}

// ReplacePackages mocks base method.
func (m *MockGigRepository) ReplacePackages(ctx context.Context, gigID string, params ReplacePackagesParams) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePackages", ctx, gigID, params)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplacePackages indicates an expected call of ReplacePackages.
func (mr *MockGigRepositoryMockRecorder) ReplacePackages(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePackages", reflect.TypeOf((*MockGigRepository)(nil).ReplacePackages), ctx, gigID, params)
}

// ReplaceQuestions mocks base method.
func (m *MockGigRepository) ReplaceQuestions(ctx context.Context, gigID string, params ReplaceQuestionsParams) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceQuestions", ctx, gigID, params)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceQuestions indicates an expected call of ReplaceQuestions.
func (mr *MockGigRepositoryMockRecorder) ReplaceQuestions(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceQuestions", reflect.TypeOf((*MockGigRepository)(nil).ReplaceQuestions), ctx, gigID, params)
}

// UpdateBasicInfo mocks base method.
func (m *MockGigRepository) UpdateBasicInfo(ctx context.Context, gigID string, params UpdateBasicInfoParams) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicInfo", ctx, gigID, params)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicInfo indicates an expected call of UpdateBasicInfo.
func (mr *MockGigRepositoryMockRecorder) UpdateBasicInfo(ctx, gigID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicInfo", reflect.TypeOf((*MockGigRepository)(nil).UpdateBasicInfo), ctx, gigID, params)
}

// UpdateSellerUsername mocks base method.
func (m *MockGigRepository) UpdateSellerUsername(ctx context.Context, gigID, sellerUsername string) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSellerUsername", ctx, gigID, sellerUsername)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSellerUsername indicates an expected call of UpdateSellerUsername.
func (mr *MockGigRepositoryMockRecorder) UpdateSellerUsername(ctx, gigID, sellerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSellerUsername", reflect.TypeOf((*MockGigRepository)(nil).UpdateSellerUsername), ctx, gigID, sellerUsername)
}

// MockGigReadRepository is a mock of GigReadRepository interface.
type MockGigReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGigReadRepositoryMockRecorder
	isgomock struct{}
}

// MockGigReadRepositoryMockRecorder is the mock recorder for MockGigReadRepository.
type MockGigReadRepositoryMockRecorder struct {
	mock *MockGigReadRepository
}

// NewMockGigReadRepository creates a new mock instance.
func NewMockGigReadRepository(ctrl *gomock.Controller) *MockGigReadRepository {
	mock := &MockGigReadRepository{ctrl: ctrl}
	mock.recorder = &MockGigReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGigReadRepository) EXPECT() *MockGigReadRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockGigReadRepository) DeleteByID(ctx context.Context, gigID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, gigID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockGigReadRepositoryMockRecorder) DeleteByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockGigReadRepository)(nil).DeleteByID), ctx, gigID)
}

// GetByID mocks base method.
func (m *MockGigReadRepository) GetByID(ctx context.Context, gigID string) (*Gig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gigID)
	ret0, _ := ret[0].(*Gig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGigReadRepositoryMockRecorder) GetByID(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGigReadRepository)(nil).GetByID), ctx, gigID)
}

// GetPopularitySnapshot mocks base method.
func (m *MockGigReadRepository) GetPopularitySnapshot(ctx context.Context, gigID string) (*GigPopularitySnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularitySnapshot", ctx, gigID)
	ret0, _ := ret[0].(*GigPopularitySnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularitySnapshot indicates an expected call of GetPopularitySnapshot.
func (mr *MockGigReadRepositoryMockRecorder) GetPopularitySnapshot(ctx, gigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularitySnapshot", reflect.TypeOf((*MockGigReadRepository)(nil).GetPopularitySnapshot), ctx, gigID)
}

// ListPopularitySnapshotsByGigIDs mocks base method.
func (m *MockGigReadRepository) ListPopularitySnapshotsByGigIDs(ctx context.Context, gigIDs []string) (map[string]*GigPopularitySnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPopularitySnapshotsByGigIDs", ctx, gigIDs)
	ret0, _ := ret[0].(map[string]*GigPopularitySnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPopularitySnapshotsByGigIDs indicates an expected call of ListPopularitySnapshotsByGigIDs.
func (mr *MockGigReadRepositoryMockRecorder) ListPopularitySnapshotsByGigIDs(ctx, gigIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPopularitySnapshotsByGigIDs", reflect.TypeOf((*MockGigReadRepository)(nil).ListPopularitySnapshotsByGigIDs), ctx, gigIDs)
}

// GetUserLookup mocks base method.
func (m *MockGigReadRepository) GetUserLookup(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLookup", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLookup indicates an expected call of GetUserLookup.
func (mr *MockGigReadRepositoryMockRecorder) GetUserLookup(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLookup", reflect.TypeOf((*MockGigReadRepository)(nil).GetUserLookup), ctx, username)
}

// ListPopularitySnapshots mocks base method.
func (m *MockGigReadRepository) ListPopularitySnapshots(ctx context.Context) ([]*GigPopularitySnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPopularitySnapshots", ctx)
	ret0, _ := ret[0].([]*GigPopularitySnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPopularitySnapshots indicates an expected call of ListPopularitySnapshots.
func (mr *MockGigReadRepositoryMockRecorder) ListPopularitySnapshots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPopularitySnapshots", reflect.TypeOf((*MockGigReadRepository)(nil).ListPopularitySnapshots), ctx)
}

// ListPreviewWindow mocks base method.
func (m *MockGigReadRepository) ListPreviewWindow(ctx context.Context, userID string, window int) (*ListPreviewGigsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPreviewWindow", ctx, userID, window)
	ret0, _ := ret[0].(*ListPreviewGigsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPreviewWindow indicates an expected call of ListPreviewWindow.
func (mr *MockGigReadRepositoryMockRecorder) ListPreviewWindow(ctx, userID, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPreviewWindow", reflect.TypeOf((*MockGigReadRepository)(nil).ListPreviewWindow), ctx, userID, window)
}

// AppendPreviewGig mocks base method.
func (m *MockGigReadRepository) AppendPreviewGig(ctx context.Context, userID string, gig *GigPreview, windowSize int, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendPreviewGig", ctx, userID, gig, windowSize, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendPreviewGig indicates an expected call of AppendPreviewGig.
func (mr *MockGigReadRepositoryMockRecorder) AppendPreviewGig(ctx, userID, gig, windowSize, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendPreviewGig", reflect.TypeOf((*MockGigReadRepository)(nil).AppendPreviewGig), ctx, userID, gig, windowSize, ttl)
}

// SetPopularitySnapshot mocks base method.
func (m *MockGigReadRepository) SetPopularitySnapshot(ctx context.Context, snapshot *GigPopularitySnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPopularitySnapshot", ctx, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPopularitySnapshot indicates an expected call of SetPopularitySnapshot.
func (mr *MockGigReadRepositoryMockRecorder) SetPopularitySnapshot(ctx, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPopularitySnapshot", reflect.TypeOf((*MockGigReadRepository)(nil).SetPopularitySnapshot), ctx, snapshot)
}

// SetUserLookup mocks base method.
func (m *MockGigReadRepository) SetUserLookup(ctx context.Context, username, userID string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserLookup", ctx, username, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserLookup indicates an expected call of SetUserLookup.
func (mr *MockGigReadRepositoryMockRecorder) SetUserLookup(ctx, username, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserLookup", reflect.TypeOf((*MockGigReadRepository)(nil).SetUserLookup), ctx, username, userID, ttl)
}

// Upsert mocks base method.
func (m *MockGigReadRepository) Upsert(ctx context.Context, gig *Gig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, gig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockGigReadRepositoryMockRecorder) Upsert(ctx, gig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockGigReadRepository)(nil).Upsert), ctx, gig)
}

// UpsertPreviewWindow mocks base method.
func (m *MockGigReadRepository) UpsertPreviewWindow(ctx context.Context, userID string, window int, gigs []*GigPreview, hasMore bool, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPreviewWindow", ctx, userID, window, gigs, hasMore, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPreviewWindow indicates an expected call of UpsertPreviewWindow.
func (mr *MockGigReadRepositoryMockRecorder) UpsertPreviewWindow(ctx, userID, window, gigs, hasMore, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPreviewWindow", reflect.TypeOf((*MockGigReadRepository)(nil).UpsertPreviewWindow), ctx, userID, window, gigs, hasMore, ttl)
}
